#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#define DRAM_2G_HYNIX_BDID    0
#define DRAM_4G_HYNIX_BDID    1
#define DRAM_2G_SAMSUNG_BDID  2
#define DRAM_4G_SAMSUNG_BDID  3

#define DRAM_2G_HYNIX_MASK       (BOARD_ID_MASK(DRAM_2G_HYNIX_BDID))
#define DRAM_4G_HYNIX_MASK       (BOARD_ID_MASK(DRAM_4G_HYNIX_BDID))
#define DRAM_2G_SAMSUNG_MASK       (BOARD_ID_MASK(DRAM_2G_SAMSUNG_BDID))
#define DRAM_4G_SAMSUNG_MASK      (BOARD_ID_MASK(DRAM_4G_SAMSUNG_BDID))

#endif
